### ISSUE TITLE
Práctica de conexión de base de datos

### ISSUE THREAD

**Issue by SANDRAVELASCO** [SistemasTecTlaxiaco/conexion-bases-de-datos-equipo-topicos-as#1]
[Practica conexion de base de datos.pdf](https://github.com/SistemasTecTlaxiaco/conexion-bases-de-datos-equipo-topicos-as/files/8697367/Practica.conexion.de.base.de.datos.pdf)

**Comment by RaelRGB** [comment]
20%

**Comment by josealfredo79** [comment]
bien hecho y revisado..
